### ISSUE TITLE
The translation and bbox in MPI-INF-3DHP

### ISSUE THREAD

**Issue by chenmingTHU** [mks0601/NeuralAnnot_RELEASE#10]
Hi mks0601 !
I am trying to visualize the SMPLXmesh driven with parameters provided in MPI-INF-3DHP_SMPLX_NeuralAnnot.json, and I used the bounding box and camera parameters provided in MPI-INF-3DHP_camera_1k.json. The pose of SMPLX mesh seemed to be right, but the rendered image had incorrect projected mesh. 

![image](https://user-images.githubusercontent.com/22796506/199634147-ffd47a4d-6525-444c-ab25-3a7ac02feca5.png)

**Comment by mks0601** [comment]
Did you try this? https://github.com/mks0601/NeuralAnnot_RELEASE/blob/main/MPI-INF-3DHP/demo_smplx.py

**Comment by chenmingTHU** [comment]
>

**Comment by chenmingTHU** [comment]
> Yes, I tried both the provided demo script and my own processing script, the above figure is the result of demo_smplx.py.

**Comment by mks0601** [comment]
![smplx](https://user-images.githubusercontent.com/13601723/199639567-44b40c6c-bb02-44c8-9168-14407252f674.jpg)
 I've just run the code without changing it.

**Comment by chenmingTHU** [comment]
> ![smplx](https://user-images.githubusercontent.com/13601723/199639567-44b40c6c-bb02-44c8-9168-14407252f674.jpg) I've just run the code without changing it.

Thanks for replying,  I found that my image (2048, 2048, 3) has different size of yours(1024, 1024). orz
