### ISSUE TITLE
Clarification on 3D joint labels

### ISSUE THREAD

**Issue by zhangy76** [mks0601/NeuralAnnot_RELEASE#11]
Hi,

May I ask what is the 3D joint positions stored in "Human36M_subject*_joint_3d.json"? Is that the 3D joint label provided in the original datasets or provide by NeuralAnnot?

Thanks,
Yufei

**Comment by mks0601** [comment]
There is no 'NeuralAnnot' in the filename, which means that is from the original dataset.

**Comment by zhangy76** [comment]
Got it and thanks for the quick reply!

Yufei
