### ISSUE TITLE
question about pseudo-GT files

### ISSUE THREAD

**Issue by canghaiyunfan** [mks0601/NeuralAnnot_RELEASE#14]
I find your offered pseudo-GT file (MSCOCO_train_MANO_NeuralAnnot.json) contain `pose`, `shape`, `trans` for mano, `focal` ,`princpt` for camera.
I want to know how to get `trans`, `focal`, `princpt`.

**Comment by mks0601** [comment]
Assuming a fixed camera intrinsnic (focal length: (5000,5000), princpt:(128,128)), I got smpl parameters with perspective camera model. Hence, I got smpl_pose, smpl_shape, and trans. Then, I multiplied an inverse affine transformation to camera intrinsic matrix K to transform cropped single person space to original image space (before crop and resize).

**Comment by canghaiyunfan** [comment]
Thanks for your reply!
I have some question about [`trans`](https://github.com/mks0601/Hand4Whole_RELEASE/blob/97ed6d8baded58992b928c701d326c5c67787446/common/utils/preprocessing.py#L260) in mano layer, Is it same as camera para that model predict?

**Comment by mks0601** [comment]
Could you clarify what 'camera para` means? Also, 'model' means a regressor? or MANO model?

**Comment by canghaiyunfan** [comment]
'camera para` is regressor predict,such as [‘cam_trans’](https://github.com/mks0601/Hand4Whole_RELEASE/blob/97ed6d8baded58992b928c701d326c5c67787446/main/model.py#L136) in this code.
'model' means a regressor. 

I want to know how to get [`trans`](https://github.com/mks0601/Hand4Whole_RELEASE/blob/97ed6d8baded58992b928c701d326c5c67787446/common/utils/preprocessing.py#L260) in mano layer when you generate pseudo-GT file.

**Comment by mks0601** [comment]
For the right hand, `trans` is exactly same with `cam_trans` of that code.
For the left hand, `trans` is `torch.stack((-cam_trans[:,0], cam_trans[:,1], cam_trans[:,2]),1)` because `cam_trans` in that code is for the right hand.

**Comment by canghaiyunfan** [comment]
Got it, Thanks very much.
