### ISSUE TITLE
Hi, the download link seems not working

### ISSUE THREAD

**Issue by stevenlsw** [mks0601/NeuralAnnot_RELEASE#21]
Dear author, 

it seems the download link for the dataset is not working, could you take a look when you have time to see if it is possible to fix it. 

Thanks!

**Comment by mks0601** [comment]
Hi, it seems there are too many download requests to my Onedrive server. Could you 1) open a Onedrive tab and login and 2) click the download link with another new tab?

**Comment by mks0601** [comment]
Hi, it seems Onedrive is not good enough to host files. I changed all hosted files back to Google drive. Please check the updated README. I guess there would be no problem now.

**Comment by stevenlsw** [comment]
Hi, thanks so much, now the links works well for me. I will close the issue.
