### ISSUE TITLE
Demo for InterHand2.6M

### ISSUE THREAD

**Issue by redorangeyellowy** [mks0601/NeuralAnnot_RELEASE#7]
Hello.

Is there any demo code for InterHand2.6M dataset?

**Comment by mks0601** [comment]
which demo?

**Comment by redorangeyellowy** [comment]
In your code, there is a demo code for another dataset (i.e. COCO, Human3.6M, MPII, etc), but I don't think there is a demo code for InterHand2.6M dataset.

**Comment by mks0601** [comment]
See this
https://github.com/facebookresearch/InterHand2.6M/blob/main/tool/MANO_render/render.py

**Comment by redorangeyellowy** [comment]
Looking closely at the code on the link, it seems to render images with mano parameters.

But, if there is an image without a mano parameter, can I reconstruct the mesh of hand image?

**Comment by mks0601** [comment]
All the demo codes in this repo is to render meshes. The above code is also for rendering meshes.

**Comment by redorangeyellowy** [comment]
https://github.com/facebookresearch/InterHand2.6M/blob/main/tool/MANO_render/render.py#L60

Then, if there is no value in the `mano_params` of the code above, isn't there an image that can't be rendered?

I wonder what I should do if I want to render these images which have no `mano_params`.

**Comment by mks0601** [comment]
There could be some cases without mano parameters as there is no enough evidence (target) to get mano parameters. Such case mainly includes invalid 3D root joint coordinates as root joint coordinate is necessary to fit MANO parameters to GT 3D joint coordinates after canceling root traslation. In such case, you can fit MANO parameters to 2D joint coordinates, but the result would be not very good to call it as 'GT MANO parameters' as fitted data to 2D suffers from depth/scale ambiguity.

**Comment by redorangeyellowy** [comment]
Okay. Thank you for your reply.
