### ISSUE TITLE
Question about results replacing only 3d annotations used in SPIN

### ISSUE THREAD

**Issue by MooreManor** [mks0601/NeuralAnnot_RELEASE#8]
@mks0601 
Hello! NeuralAnnot is a wonderful work. I have a question about the experiment.

For SPIN used 3D dataset labels, that is, h36m mosh labels and mpi-inf-3dhp_mview_fits, will substituting NeuralAnnot pseudo labels with them raise the score (i.e. indirect 3d annotation error) while keeping ITW datasets labels with the same 2D GT annots without GT SMPL supervision?

**Comment by mks0601** [comment]
I checked that their h36m and mpi-inf-3dhp fits are worse than NeuralAnnot's fits.

**Comment by MooreManor** [comment]
@mks0601 Is the comparision conducted through indirect 3d annotation error or visualization?

**Comment by mks0601** [comment]
I checked the direct 3D annotation error

**Comment by MooreManor** [comment]
@mks0601 Is it possible to give the detailed number of the direct 3D annotation error between the neuralAnnot and the original one? Thanks!

**Comment by mks0601** [comment]
Sorry I don't remember exact numbers.. But I remember there was some meaningful gap

**Comment by MooreManor** [comment]
@mks0601 Then how about the indirect 3d annotation error if you have done related experiments? Besides, do you try to compare the quality of annots with the latest [CLIFF](https://github.com/huawei-noah/noah-research/tree/master/CLIFF) on ITW dataset?

**Comment by mks0601** [comment]
For both, I haven't done related experiments. Sorry about this

**Comment by MooreManor** [comment]
@mks0601 Thanks for your patient and in-time reply! I am clear now :) 👍
